### ISSUE TITLE
script not running in root user 

### ISSUE THREAD

**Issue by 0xMrR0b0t** [GoDzM4TT3O/dotfiles#1]
![image](https://user-images.githubusercontent.com/53564887/209842458-f78aaca6-1c7c-4bc5-9a8e-0a5f0f7a3e66.png)

**Comment by saloniamatteo** [comment]
Hi,
the script is not meant to be ran as root -- why are you even trying to get dotfiles on Kali? It is not meant to be daily driven like you would with any other distro.

Anyway, Kali's user policy ([Kali's Default Credentials][KDC], [Kali User Policy][KUP]) was changed in 2020 (almost 3 years ago!) to allow non-root users, so you really should be using a non-root user to run the installation script -- if you're stubborn enough to keep using Kali.

If you really really want to run the installation script under the root user, remove the two following lines, in order to not check which user is running the script:

https://github.com/saloniamatteo/dotfiles/blob/eaf0dfd5df2bdc686c6c82c2c79efb7a6e7a1c1f/install.sh#L14-L15

You can also remove the `get_root()` function, found below these two lines.

[KDC]: https://www.kali.org/docs/introduction/default-credentials
[KUP]: https://www.kali.org/docs/policy/kali-linux-user-policy

**Comment by saloniamatteo** [comment]
This behaviour is not supported and is discouraged, locking the conversation.
